vse: &vse
  docker:
    - image: circleci/node:8.11.3
  ansible:
  docker: &ansible
    - image: 'circleci/python:latest'
      environment:
          ANSIBLE_HOST_KEY_CHECKING: no

version: 2.1
orbs:
  ansible-playbook: orbss/ansible-playbook@0.0.5
jobs:
  build:
    <<: *vse
    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - .
    deploy:
    docker: *ansible
    steps:
      - attach_workspace:
          at: .
      - ansible-playbook/install
      - run:
         command:
          sudo pip install ansible boto boto3
      - add_ssh_keys:
          fingerprints:
            - "95:4c:a6:44:44:27:13:ac:87:e1:6f:cf:84:cc:8b:f0"
      - run: echo $SSH_PRIVATE_KEY | sed 's/<CRLF>/\n/g' > devops.pem
      - run: chmod 400 devops.pem
      - ansible-playbook/playbook:
          playbook: ./ansible/ec2_deploy.yml
          playbook-options: --user ubuntu --key-file devops.pem
workflows:
  version: 2.1
  build:
    jobs:
      - build
      - deploy:
         requires:
            - build
         filters:
            branches:
               only: master